package com.nienluan.htbldt.model;
// default package
// Generated Sep 23, 2014 11:02:41 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BaiDanhGia generated by hbm2java
 */
@Entity
@Table(name = "bai_danh_gia", catalog = "nienluan")
public class BaiDanhGia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4419384965870615016L;
	private Integer maBaiDg;
	private DienThoai dienThoai;
	private Date tgTaoDg;
	private String noiDung;
	private String ghiChuDg;

	public BaiDanhGia() {
	}

	public BaiDanhGia(DienThoai dienThoai) {
		this.dienThoai = dienThoai;
	}

	public BaiDanhGia(DienThoai dienThoai, Date tgTaoDg, String noiDung,
			String ghiChuDg) {
		this.dienThoai = dienThoai;
		this.tgTaoDg = tgTaoDg;
		this.noiDung = noiDung;
		this.ghiChuDg = ghiChuDg;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MA_BAI_DG", unique = true, nullable = false)
	public Integer getMaBaiDg() {
		return this.maBaiDg;
	}

	public void setMaBaiDg(Integer maBaiDg) {
		this.maBaiDg = maBaiDg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MA_DT", nullable = false)
	public DienThoai getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(DienThoai dienThoai) {
		this.dienThoai = dienThoai;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TG_TAO_DG", length = 19)
	public Date getTgTaoDg() {
		return this.tgTaoDg;
	}

	public void setTgTaoDg(Date tgTaoDg) {
		this.tgTaoDg = tgTaoDg;
	}

	@Column(name = "NOI_DUNG", length = 65535)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

	@Column(name = "GHI_CHU_DG", length = 200)
	public String getGhiChuDg() {
		return this.ghiChuDg;
	}

	public void setGhiChuDg(String ghiChuDg) {
		this.ghiChuDg = ghiChuDg;
	}

}
