package com.nienluan.htbldt.model;
// default package
// Generated Sep 23, 2014 11:02:41 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * BinhLuanDt generated by hbm2java
 */
@Entity
@Table(name = "binh_luan_dt", catalog = "nienluan")
public class BinhLuanDt implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 787127994458235851L;
	private int maBl;
	private BinhLuan binhLuan;
	private DienThoai dienThoai;

	public BinhLuanDt() {
	}

	public BinhLuanDt(BinhLuan binhLuan, DienThoai dienThoai) {
		this.binhLuan = binhLuan;
		this.dienThoai = dienThoai;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "binhLuan"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "MA_BL", unique = true, nullable = false)
	public int getMaBl() {
		return this.maBl;
	}

	public void setMaBl(int maBl) {
		this.maBl = maBl;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public BinhLuan getBinhLuan() {
		return this.binhLuan;
	}

	public void setBinhLuan(BinhLuan binhLuan) {
		this.binhLuan = binhLuan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MA_DT", nullable = false)
	public DienThoai getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(DienThoai dienThoai) {
		this.dienThoai = dienThoai;
	}

}
