package com.nienluan.htbldt.model;
// default package
// Generated Sep 23, 2014 11:02:41 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BinhLuan generated by hbm2java
 */
@Entity
@Table(name = "binh_luan", catalog = "nienluan")
public class BinhLuan implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5130890823290551738L;
	private Integer maBl;
	private TaiKhoan taiKhoan;
	private Date thoiGianBl;
	private String noiDungBl;
	private Integer baoViPham;
	private BinhLuanDt binhLuanDt;
	private Set<BlPhu> blPhusForMaBlC = new HashSet<BlPhu>(0);
	private BlPhu blPhuByMaBl;

	public BinhLuan() {
	}

	public BinhLuan(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

	public BinhLuan(TaiKhoan taiKhoan, Date thoiGianBl, String noiDungBl,
			Integer baoViPham, BinhLuanDt binhLuanDt,
			Set<BlPhu> blPhusForMaBlC, BlPhu blPhuByMaBl) {
		this.taiKhoan = taiKhoan;
		this.thoiGianBl = thoiGianBl;
		this.noiDungBl = noiDungBl;
		this.baoViPham = baoViPham;
		this.binhLuanDt = binhLuanDt;
		this.blPhusForMaBlC = blPhusForMaBlC;
		this.blPhuByMaBl = blPhuByMaBl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MA_BL", unique = true, nullable = false)
	public Integer getMaBl() {
		return this.maBl;
	}

	public void setMaBl(Integer maBl) {
		this.maBl = maBl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MA_TK", nullable = false)
	public TaiKhoan getTaiKhoan() {
		return this.taiKhoan;
	}

	public void setTaiKhoan(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "THOI_GIAN_BL", length = 19)
	public Date getThoiGianBl() {
		return this.thoiGianBl;
	}

	public void setThoiGianBl(Date thoiGianBl) {
		this.thoiGianBl = thoiGianBl;
	}

	@Column(name = "NOI_DUNG_BL", length = 500)
	public String getNoiDungBl() {
		return this.noiDungBl;
	}

	public void setNoiDungBl(String noiDungBl) {
		this.noiDungBl = noiDungBl;
	}

	@Column(name = "BAO_VI_PHAM")
	public Integer getBaoViPham() {
		return this.baoViPham;
	}

	public void setBaoViPham(Integer baoViPham) {
		this.baoViPham = baoViPham;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "binhLuan")
	public BinhLuanDt getBinhLuanDt() {
		return this.binhLuanDt;
	}

	public void setBinhLuanDt(BinhLuanDt binhLuanDt) {
		this.binhLuanDt = binhLuanDt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "binhLuanByMaBlC")
	public Set<BlPhu> getBlPhusForMaBlC() {
		return this.blPhusForMaBlC;
	}

	public void setBlPhusForMaBlC(Set<BlPhu> blPhusForMaBlC) {
		this.blPhusForMaBlC = blPhusForMaBlC;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "binhLuanByMaBl")
	public BlPhu getBlPhuByMaBl() {
		return this.blPhuByMaBl;
	}

	public void setBlPhuByMaBl(BlPhu blPhuByMaBl) {
		this.blPhuByMaBl = blPhuByMaBl;
	}

}
