package com.nienluan.htbldt.model;
// default package
// Generated Sep 23, 2014 11:02:41 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DonDatHang generated by hbm2java
 */
@Entity
@Table(name = "don_dat_hang", catalog = "nienluan")
public class DonDatHang implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9188127569325807426L;
	private Integer maDonDh;
	private TaiKhoan taiKhoan;
	private String dcGiaoHang;
	private String sdtNhan;
	private String ghiChuKhac;
	private Date thoiGianTao;
	private Boolean trangThai;
	private Set<MucDh> mucDhs = new HashSet<MucDh>(0);

	public DonDatHang() {
	}

	public DonDatHang(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

	public DonDatHang(TaiKhoan taiKhoan, String dcGiaoHang, String sdtNhan,
			String ghiChuKhac, Date thoiGianTao, Boolean trangThai,
			Set<MucDh> mucDhs) {
		this.taiKhoan = taiKhoan;
		this.dcGiaoHang = dcGiaoHang;
		this.sdtNhan = sdtNhan;
		this.ghiChuKhac = ghiChuKhac;
		this.thoiGianTao = thoiGianTao;
		this.trangThai = trangThai;
		this.mucDhs = mucDhs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MA_DON_DH", unique = true, nullable = false)
	public Integer getMaDonDh() {
		return this.maDonDh;
	}

	public void setMaDonDh(Integer maDonDh) {
		this.maDonDh = maDonDh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MA_TK", nullable = false)
	public TaiKhoan getTaiKhoan() {
		return this.taiKhoan;
	}

	public void setTaiKhoan(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

	@Column(name = "DC_GIAO_HANG", length = 200)
	public String getDcGiaoHang() {
		return this.dcGiaoHang;
	}

	public void setDcGiaoHang(String dcGiaoHang) {
		this.dcGiaoHang = dcGiaoHang;
	}

	@Column(name = "SDT_NHAN", length = 20)
	public String getSdtNhan() {
		return this.sdtNhan;
	}

	public void setSdtNhan(String sdtNhan) {
		this.sdtNhan = sdtNhan;
	}

	@Column(name = "GHI_CHU_KHAC", length = 200)
	public String getGhiChuKhac() {
		return this.ghiChuKhac;
	}

	public void setGhiChuKhac(String ghiChuKhac) {
		this.ghiChuKhac = ghiChuKhac;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "THOI_GIAN_TAO", length = 19)
	public Date getThoiGianTao() {
		return this.thoiGianTao;
	}

	public void setThoiGianTao(Date thoiGianTao) {
		this.thoiGianTao = thoiGianTao;
	}

	@Column(name = "TRANG_THAI")
	public Boolean getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(Boolean trangThai) {
		this.trangThai = trangThai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donDatHang")
	public Set<MucDh> getMucDhs() {
		return this.mucDhs;
	}

	public void setMucDhs(Set<MucDh> mucDhs) {
		this.mucDhs = mucDhs;
	}

}
