package com.nienluan.htbldt.model;
// default package
// Generated Sep 23, 2014 11:02:41 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DonGia generated by hbm2java
 */
@Entity
@Table(name = "don_gia", catalog = "nienluan")
public class DonGia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1727027963731249550L;
	private Integer maGia;
	private DienThoai dienThoai;
	private Integer gia;
	private Integer giaKm;
	private String donVi;
	private Date tgTaoGia;
	private Set<MucDh> mucDhs = new HashSet<MucDh>(0);

	public DonGia() {
	}

	public DonGia(DienThoai dienThoai) {
		this.dienThoai = dienThoai;
	}

	public DonGia(DienThoai dienThoai, Integer gia, Integer giaKm,
			String donVi, Date tgTaoGia, Set<MucDh> mucDhs) {
		this.dienThoai = dienThoai;
		this.gia = gia;
		this.giaKm = giaKm;
		this.donVi = donVi;
		this.tgTaoGia = tgTaoGia;
		this.mucDhs = mucDhs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MA_GIA", unique = true, nullable = false)
	public Integer getMaGia() {
		return this.maGia;
	}

	public void setMaGia(Integer maGia) {
		this.maGia = maGia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MA_DT", nullable = false)
	public DienThoai getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(DienThoai dienThoai) {
		this.dienThoai = dienThoai;
	}

	@Column(name = "GIA")
	public Integer getGia() {
		return this.gia;
	}

	public void setGia(Integer gia) {
		this.gia = gia;
	}

	@Column(name = "GIA_KM")
	public Integer getGiaKm() {
		return this.giaKm;
	}

	public void setGiaKm(Integer giaKm) {
		this.giaKm = giaKm;
	}

	@Column(name = "DON_VI", length = 10)
	public String getDonVi() {
		return this.donVi;
	}

	public void setDonVi(String donVi) {
		this.donVi = donVi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TG_TAO_GIA", length = 19)
	public Date getTgTaoGia() {
		return this.tgTaoGia;
	}

	public void setTgTaoGia(Date tgTaoGia) {
		this.tgTaoGia = tgTaoGia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donGia")
	public Set<MucDh> getMucDhs() {
		return this.mucDhs;
	}

	public void setMucDhs(Set<MucDh> mucDhs) {
		this.mucDhs = mucDhs;
	}

	@Override
	public String toString() {
		return "DonGia [maGia=" + maGia + ", gia=" + gia + ", giaKm=" + giaKm
				+ ", donVi=" + donVi + ", tgTaoGia=" + tgTaoGia + "]";
	}

}
