package com.nienluan.htbldt.model;
// default package
// Generated Sep 23, 2014 11:02:41 PM by Hibernate Tools 4.0.0

import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HinhAnh generated by hbm2java
 */
@Entity
@Table(name = "hinh_anh", catalog = "nienluan")
public class HinhAnh implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1294529448648567654L;
	private Integer maAnh;
	private Blob data;
	private Long sizeData;
	private String type;
	private Date time;
	private Set<ThongBao> thongBaos = new HashSet<ThongBao>(0);
	private AnhDt anhDt;

	public HinhAnh() {
	}

	public HinhAnh(Blob data, Long sizeData, String type, Date time,
			Set<ThongBao> thongBaos, AnhDt anhDt) {
		this.data = data;
		this.sizeData = sizeData;
		this.type = type;
		this.time = time;
		this.thongBaos = thongBaos;
		this.anhDt = anhDt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MA_ANH", unique = true, nullable = false)
	public Integer getMaAnh() {
		return this.maAnh;
	}

	public void setMaAnh(Integer maAnh) {
		this.maAnh = maAnh;
	}

	@Column(name = "DATA")
	public Blob getData() {
		return this.data;
	}

	public void setData(Blob data) {
		this.data = data;
	}

	@Column(name = "SIZE_DATA")
	public Long getSizeData() {
		return this.sizeData;
	}

	public void setSizeData(Long sizeData) {
		this.sizeData = sizeData;
	}

	@Column(name = "TYPE", length = 65535)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIME", length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hinhAnh")
	public Set<ThongBao> getThongBaos() {
		return this.thongBaos;
	}

	public void setThongBaos(Set<ThongBao> thongBaos) {
		this.thongBaos = thongBaos;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "hinhAnh")
	public AnhDt getAnhDt() {
		return this.anhDt;
	}

	public void setAnhDt(AnhDt anhDt) {
		this.anhDt = anhDt;
	}

	@Override
	public String toString() {
		return "HinhAnh [maAnh=" + maAnh + ", sizeData=" + sizeData + ", type="
				+ type + ", time=" + time + "]";
	}

}
