package com.nienluan.htbldt.model;
// default package
// Generated Sep 23, 2014 11:02:41 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoaiTk generated by hbm2java
 */
@Entity
@Table(name = "loai_tk", catalog = "nienluan")
public class LoaiTk implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7054825346124085217L;
	private Integer maLoaiTk;
	private String tenLoaiTk;
	private String ghiChuLoaiTk;
	private Set<TaiKhoan> taiKhoans = new HashSet<TaiKhoan>(0);

	public LoaiTk() {
	}

	public LoaiTk(String tenLoaiTk, String ghiChuLoaiTk, Set<TaiKhoan> taiKhoans) {
		this.tenLoaiTk = tenLoaiTk;
		this.ghiChuLoaiTk = ghiChuLoaiTk;
		this.taiKhoans = taiKhoans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MA_LOAI_TK", unique = true, nullable = false)
	public Integer getMaLoaiTk() {
		return this.maLoaiTk;
	}

	public void setMaLoaiTk(Integer maLoaiTk) {
		this.maLoaiTk = maLoaiTk;
	}

	@Column(name = "TEN_LOAI_TK", length = 50)
	public String getTenLoaiTk() {
		return this.tenLoaiTk;
	}

	public void setTenLoaiTk(String tenLoaiTk) {
		this.tenLoaiTk = tenLoaiTk;
	}

	@Column(name = "GHI_CHU_LOAI_TK", length = 200)
	public String getGhiChuLoaiTk() {
		return this.ghiChuLoaiTk;
	}

	public void setGhiChuLoaiTk(String ghiChuLoaiTk) {
		this.ghiChuLoaiTk = ghiChuLoaiTk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaiTk")
	public Set<TaiKhoan> getTaiKhoans() {
		return this.taiKhoans;
	}

	public void setTaiKhoans(Set<TaiKhoan> taiKhoans) {
		this.taiKhoans = taiKhoans;
	}

}
