package com.nienluan.htbldt.model;
// default package
// Generated Sep 23, 2014 11:02:41 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MucDhId generated by hbm2java
 */
@Embeddable
public class MucDhId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2238281412391120139L;
	private int maGia;
	private int maDonDh;

	public MucDhId() {
	}

	public MucDhId(int maGia, int maDonDh) {
		this.maGia = maGia;
		this.maDonDh = maDonDh;
	}

	@Column(name = "MA_GIA", nullable = false)
	public int getMaGia() {
		return this.maGia;
	}

	public void setMaGia(int maGia) {
		this.maGia = maGia;
	}

	@Column(name = "MA_DON_DH", nullable = false)
	public int getMaDonDh() {
		return this.maDonDh;
	}

	public void setMaDonDh(int maDonDh) {
		this.maDonDh = maDonDh;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MucDhId))
			return false;
		MucDhId castOther = (MucDhId) other;

		return (this.getMaGia() == castOther.getMaGia())
				&& (this.getMaDonDh() == castOther.getMaDonDh());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaGia();
		result = 37 * result + this.getMaDonDh();
		return result;
	}

}
