package com.nienluan.htbldt.model;
// default package
// Generated Sep 23, 2014 11:02:41 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MucDh generated by hbm2java
 */
@Entity
@Table(name = "muc_dh", catalog = "nienluan")
public class MucDh implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7361029577870894604L;
	private MucDhId id;
	private DonGia donGia;
	private DonDatHang donDatHang;
	private Integer soLuong;

	public MucDh() {
	}

	public MucDh(MucDhId id, DonGia donGia, DonDatHang donDatHang) {
		this.id = id;
		this.donGia = donGia;
		this.donDatHang = donDatHang;
	}

	public MucDh(MucDhId id, DonGia donGia, DonDatHang donDatHang,
			Integer soLuong) {
		this.id = id;
		this.donGia = donGia;
		this.donDatHang = donDatHang;
		this.soLuong = soLuong;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "maGia", column = @Column(name = "MA_GIA", nullable = false)),
			@AttributeOverride(name = "maDonDh", column = @Column(name = "MA_DON_DH", nullable = false)) })
	public MucDhId getId() {
		return this.id;
	}

	public void setId(MucDhId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MA_GIA", nullable = false, insertable = false, updatable = false)
	public DonGia getDonGia() {
		return this.donGia;
	}

	public void setDonGia(DonGia donGia) {
		this.donGia = donGia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MA_DON_DH", nullable = false, insertable = false, updatable = false)
	public DonDatHang getDonDatHang() {
		return this.donDatHang;
	}

	public void setDonDatHang(DonDatHang donDatHang) {
		this.donDatHang = donDatHang;
	}

	@Column(name = "SO_LUONG")
	public Integer getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(Integer soLuong) {
		this.soLuong = soLuong;
	}

}
