package com.nienluan.htbldt.model;
// default package
// Generated Sep 23, 2014 11:02:41 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PhanHeDt generated by hbm2java
 */
@Entity
@Table(name = "phan_he_dt", catalog = "nienluan")
public class PhanHeDt implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1475720667221154503L;
	private Integer maPhanHe;
	private HangSx hangSx;
	private String tenPhanHe;
	private String ghiChuPh;
	private Set<DienThoai> dienThoais = new HashSet<DienThoai>(0);

	public PhanHeDt() {
	}

	public PhanHeDt(HangSx hangSx) {
		this.hangSx = hangSx;
	}

	public PhanHeDt(HangSx hangSx, String tenPhanHe, String ghiChuPh,
			Set<DienThoai> dienThoais) {
		this.hangSx = hangSx;
		this.tenPhanHe = tenPhanHe;
		this.ghiChuPh = ghiChuPh;
		this.dienThoais = dienThoais;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MA_PHAN_HE", unique = true, nullable = false)
	public Integer getMaPhanHe() {
		return this.maPhanHe;
	}

	public void setMaPhanHe(Integer maPhanHe) {
		this.maPhanHe = maPhanHe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MA_HANG_SX", nullable = false)
	public HangSx getHangSx() {
		return this.hangSx;
	}

	public void setHangSx(HangSx hangSx) {
		this.hangSx = hangSx;
	}

	@Column(name = "TEN_PHAN_HE", length = 50)
	public String getTenPhanHe() {
		return this.tenPhanHe;
	}

	public void setTenPhanHe(String tenPhanHe) {
		this.tenPhanHe = tenPhanHe;
	}

	@Column(name = "GHI_CHU_PH", length = 200)
	public String getGhiChuPh() {
		return this.ghiChuPh;
	}

	public void setGhiChuPh(String ghiChuPh) {
		this.ghiChuPh = ghiChuPh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phanHeDt")
	public Set<DienThoai> getDienThoais() {
		return this.dienThoais;
	}

	public void setDienThoais(Set<DienThoai> dienThoais) {
		this.dienThoais = dienThoais;
	}

	@Override
	public String toString() {
		return "PhanHeDt [maPhanHe=" + maPhanHe + ", tenPhanHe=" + tenPhanHe
				+ ", ghiChuPh=" + ghiChuPh + "]";
	}

}
