package com.nienluan.htbldt.model;
// default package
// Generated Sep 23, 2014 11:02:41 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThongBao generated by hbm2java
 */
@Entity
@Table(name = "thong_bao", catalog = "nienluan")
public class ThongBao implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7879845705744153592L;
	private Integer maTb;
	private HinhAnh hinhAnh;
	private TaiKhoan taiKhoan;
	private String tieuDeTb;
	private String noiDungTb;
	private Date thoiGianTb;

	public ThongBao() {
	}

	public ThongBao(HinhAnh hinhAnh, TaiKhoan taiKhoan) {
		this.hinhAnh = hinhAnh;
		this.taiKhoan = taiKhoan;
	}

	public ThongBao(HinhAnh hinhAnh, TaiKhoan taiKhoan, String tieuDeTb,
			String noiDungTb, Date thoiGianTb) {
		this.hinhAnh = hinhAnh;
		this.taiKhoan = taiKhoan;
		this.tieuDeTb = tieuDeTb;
		this.noiDungTb = noiDungTb;
		this.thoiGianTb = thoiGianTb;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MA_TB", unique = true, nullable = false)
	public Integer getMaTb() {
		return this.maTb;
	}

	public void setMaTb(Integer maTb) {
		this.maTb = maTb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MA_ANH", nullable = false)
	public HinhAnh getHinhAnh() {
		return this.hinhAnh;
	}

	public void setHinhAnh(HinhAnh hinhAnh) {
		this.hinhAnh = hinhAnh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MA_TK", nullable = false)
	public TaiKhoan getTaiKhoan() {
		return this.taiKhoan;
	}

	public void setTaiKhoan(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

	@Column(name = "TIEU_DE_TB", length = 100)
	public String getTieuDeTb() {
		return this.tieuDeTb;
	}

	public void setTieuDeTb(String tieuDeTb) {
		this.tieuDeTb = tieuDeTb;
	}

	@Column(name = "NOI_DUNG_TB", length = 65535)
	public String getNoiDungTb() {
		return this.noiDungTb;
	}

	public void setNoiDungTb(String noiDungTb) {
		this.noiDungTb = noiDungTb;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "THOI_GIAN_TB", length = 19)
	public Date getThoiGianTb() {
		return this.thoiGianTb;
	}

	public void setThoiGianTb(Date thoiGianTb) {
		this.thoiGianTb = thoiGianTb;
	}

	@Override
	public String toString() {
		return "ThongBao [maTb=" + maTb + ", tieuDeTb=" + tieuDeTb
				+ ", noiDungTb=" + noiDungTb + ", thoiGianTb=" + thoiGianTb
				+ "]";
	}

}
